swfl-coders/tech-alliance-website

- pages/index.js
- styles/Home.module.css
- utils/config.js
> Add groups cards

- utils/config.js
Hi @zarela ! Please find the code for this issue: https://github.com/swfl-coders/tech-alliance-website/issues/3
Let me know if it looks ok/needs to be updated. Thanks :)
> Adds tech alliance group description and meetup link

- components/Card/Card.module.css
- package-lock.json
I thought it would be so cool if when we hoovered over a link a gradient background would show the user they are over a link. Any objections on the style/colors/design/ideal lol are of course welcome!
https://user-images.githubusercontent.com/50384386/196022087-7a4d35bb-9fa4-4125-8c0f-97a54b211303.mp4
> Cards Design

- pages/index.js
- styles/Home.module.css
Closes #21 
It also renames class that wasn't being used and is now being used in this section.
> Adds ABOUT section and fixes styles

- components/Card/Card.module.css
- components/Footer/Footer.module.css
- components/Header/Header.module.css
- pages/index.js
- styles/globals.css
> Changes styles theme to match new logo

- components/Header/Header.module.css
- Changes header background that clashes with logo
- Makes header sticky
**BEFORE:**
**AFTER:**
> Styles sticky header

- README.md
- package-lock.json
- package.json
Docs:
https://nextjs.org/docs/app/building-your-application/upgrading/version-14
Closes #23
> Upgrades to NextJS v14 and adds needed dependencies

- package-lock.json
- package.json
- pages/api/meetup.js
- pages/events.js
> Add events route

- utils/config.js
All groups are added alphabetically
Closes #30
> Updates cards with new groups

- components/Footer/Footer.jsx
Changes link from FB group to official page
> Updates facebook link on footer

- README.md
> Adds another period to the branch naming overview through VS Code.

- components/Card/Card.jsx
- package-lock.json
- package.json
- pages/index.js
- utils/config.js
working on issue #50 
Still haven't styled the icons as Tailwind has not been configured yet.
> add react-social-icons for each groups social media icon links

- package-lock.json
- package.json
- postcss.config.js
- styles/globals.css
- tailwind.config.js
- Installed tailwindcss according to tailwind website for next.js framework
- Checked to see if it worked before submitting PR
- Works well
> Implement tailwindcss 

- CONTRIBUTE.md
- components/Header/Header.jsx
- components/Header/Navigation.jsx
- components/Layout/Layout.jsx
- package-lock.json
- package.json
- pages/index.js
Navigation implemented
Responsive 
Desktop expanded
Sticky
>   implemented navigation for desktop, mobile and responsive.

- __tests__/setup/setup.js
- package-lock.json
- package.json
- vitest.config.js
In addition to my contribution for issue #71 I added support for DOM testing using jsdom
> Added support for js-dom testing. Added faker-js to dev deps

- components/Buttons/SocialButtons.jsx
- components/Logos/Logos.jsx
- pages/index.js
- tailwind.config.js
BEFORE
AFTER:
Also fixed the banner of all logos to use logos instead of a picture with all of them
> Update banner logos

- components/Header/Navigation.jsx
- pages/calendar.js
- utils/config.js
Created the Calendar button and added the calendar view of all tech alliance events. 
This is for #52
> Create Calendar Page for Tech Alliance Events

- components/Header/Navigation.jsx
- pages/calendar.js
- utils/config.js
Adds calendar and button at nav
---------
> Create Calendar Page for Tech Alliance Events (#102)

- components/Logos/Logos.jsx
- pages/api/meetup.js
- utils/config.js
Updates new links since we changed the name of the group from Music Producers to Music Makers
> Updates Music Makers new links and socials

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> Adds PR template

- .github/PULL_REQUEST_TEMPLATE.md
- utils/config.js
There is a new date for Hackerspace meetings
Update Copy
> Hs copy update

- utils/config.js
Updating from Main
Updating from Main
> Updates Hackerspace copy

- README.md
Missing live site link
Add link
> Adds site to readme
